#ifndef CHIP8_KEYBOARD_H
#define CHIP8_KEYBOARD_H

#include <SDL2/SDL.h>

const SDL_Scancode CHIP8_KEYMAP[16] = {
    SDL_SCANCODE_1, SDL_SCANCODE_2, SDL_SCANCODE_3, SDL_SCANCODE_4,
    SDL_SCANCODE_Q, SDL_SCANCODE_W, SDL_SCANCODE_E, SDL_SCANCODE_R,
    SDL_SCANCODE_A, SDL_SCANCODE_S, SDL_SCANCODE_D, SDL_SCANCODE_F,
    SDL_SCANCODE_Z, SDL_SCANCODE_X, SDL_SCANCODE_C, SDL_SCANCODE_V};

int chip8_is_key_pressed(uint8_t key);

#endif